query FindRepoByID($id: ID!){
  node(id: $id) {
    id,
    __typename,
    ...on Repository {
    pullRequests {
        __typename,
     	totalCount 
   	},
    stargazerCount,
    licenseInfo {
      	__typename,
      	name
    }
    watchers {
     	 __typename,
      	totalCount
    }
    homepageUrl,
    name,
    description,
	primaryLanguage {
		color,
		name
	}
    isInOrganization,
    owner {
      	__typename,
      	id,
		avatarUrl,
      	login
    },
    forkCount,
    description,
    issues(first: 5, filterBy: { states: OPEN }, orderBy: { field: CREATED_AT, direction: DESC }) {
      totalCount,
      edges {
        node {
          __typename,
          id,
          title,
          publishedAt,
          number,
          comments {
            __typename,
            totalCount
          }
        }
      }
    }
    }
  }
}